# fly.toml app configuration file generated for blog-api-project-young-log-1285 on 2024-07-21T17:22:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-api-project-young-log-1285'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'
  VITE_BACKEND_URL = 'https://blog-api-backend-g3af.onrender.com/'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
