name: Backend deployment to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Render.com
      env:
        RENDER_HOOK_URL: ${{ secrets.RENDER_HOOK_URL }}
      run: |
        curl -X POST $RENDER_HOOK_URL
  deploy-flyio:
    name: Deploy frontend to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd frontend-blog-api
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
