name: Unit-test pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SECRET: ${{ secrets.SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --prefix backend-blog-api

    - name: Run tests
      run: npm test --prefix backend-blog-api
  tag_release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
