name: Unit-test pipeline

on:
  push:
    branches:
      - main

env:
  SECRET: ${{ secrets.SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --prefix backend-blog-api

    - name: Run tests
      run: npm test --prefix backend-blog-api
